name: user_command
description: A generic user command class that can be used on multiple Command Widgets (with easy to use style classes).
version: 0.0.2
homepage: https://github.com/efficientyboosters/user_command
repository: https://github.com/efficientyboosters/user_command

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  overflow_view: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

